#!/usr/bin/env Rscript
args <- commandArgs(trailingOnly = TRUE)
infile <- ifelse(length(args) >= 1, args[[1]], "data/metadata/species_reference_chrM_summary.tsv")
out_results <- ifelse(length(args) >= 2, args[[2]], "results/preprocessing/reference_materialization/reference_materialization_manifest.tsv")
out_manifest <- ifelse(length(args) >= 3, args[[3]], "references/manifests/reference_materialization_manifest.tsv")
source("preprocessing/R/read_preprocessing_inputs.R")
source("preprocessing/R/reference_manifest_helpers.R")
df <- read_tsv_flexible(infile)
# tolerate either target_species or species from discovery/preprint inputs
if (!"target_species" %in% names(df)) df$target_species <- if ("species" %in% names(df)) df$species else ""
needed <- c("target_species","sample_count","preprint_REFERENCE_SPECIES","REFERENCE_SPECIES","final_wg_ref_species","final_wg_ref_source","final_wg_assembly_accession","final_wg_assembly_level","final_wg_ftp_path","final_chrM_species","final_chrM_source","final_chrM_accession","final_chrM_contig_name","final_chrM_length","final_chrM_assembly_accession","final_chrM_assembly_source","final_chrM_genbank_accn","final_chrM_refseq_accn","final_chrM_ucsc_name","final_reference_strategy")
df <- ensure_columns(df, needed)
df$preprint_REFERENCE_SPECIES <- coalesce_chr(df$preprint_REFERENCE_SPECIES, df$REFERENCE_SPECIES)
df$chrM_reference_context <- classify_chrM_context(df$final_chrM_source, df$final_chrM_accession, df$final_chrM_assembly_accession, df$final_wg_assembly_accession, df$final_chrM_length)
df$chrM_extraction_strategy <- ifelse(df$chrM_reference_context == "embedded_in_wg_ref", "extract_from_wg_fasta", ifelse(df$chrM_reference_context == "independent_chrM_ref", "download_or_extract_independent_chrM", "manual_review"))
df$chrM_source_fasta_type <- ifelse(df$chrM_reference_context == "embedded_in_wg_ref", "whole_genome_fasta", ifelse(df$chrM_reference_context == "independent_chrM_ref", "mitochondrial_fasta", "unknown"))
df$chrM_source_accession <- coalesce_chr(df$final_chrM_accession, df$final_chrM_refseq_accn, df$final_chrM_genbank_accn)
df$chrM_source_assembly_accession <- coalesce_chr(df$final_chrM_assembly_accession)
df$chrM_source_contig_name <- coalesce_chr(df$final_chrM_contig_name, df$final_chrM_refseq_accn, df$final_chrM_genbank_accn, df$final_chrM_accession)
df$wg_expected_output_fasta <- ifelse(coalesce_chr(df$final_wg_assembly_accession) == "", "", file.path("references/wg", df$final_wg_assembly_accession, paste0(df$final_wg_assembly_accession, ".genome.fa.gz")))
chr_fallback <- paste0(safe_token(df$target_species), ".chrM.fa")
df$chrM_expected_output_fasta <- ifelse(df$chrM_reference_context == "embedded_in_wg_ref", file.path("references/chrM/embedded_from_wg", paste0(df$final_wg_assembly_accession, ".chrM.fa")), ifelse(df$chrM_reference_context == "independent_chrM_ref", file.path("references/chrM/independent", ifelse(coalesce_chr(df$final_chrM_accession) == "", chr_fallback, paste0(df$final_chrM_accession, ".fa"))), ""))
df$reference_pairing_status <- reference_pairing_status(df$target_species, df$final_wg_ref_species, df$final_chrM_species)
df$final_reference_strategy <- coalesce_chr(df$final_reference_strategy, paste(df$reference_pairing_status, df$chrM_reference_context, sep = ";"))
df$manual_review_reason <- manual_review_reasons(df)
df$manual_review_required <- ifelse(df$manual_review_reason == "", "no", "yes")
cols <- c("target_species","sample_count","preprint_REFERENCE_SPECIES","final_wg_ref_species","final_wg_ref_source","final_wg_assembly_accession","final_wg_assembly_level","final_wg_ftp_path","final_chrM_species","final_chrM_source","final_chrM_accession","final_chrM_contig_name","final_chrM_length","final_chrM_assembly_accession","final_chrM_assembly_source","final_chrM_genbank_accn","final_chrM_refseq_accn","chrM_reference_context","chrM_extraction_strategy","chrM_source_fasta_type","chrM_source_accession","chrM_source_assembly_accession","chrM_source_contig_name","wg_expected_output_fasta","chrM_expected_output_fasta","reference_pairing_status","final_reference_strategy","manual_review_required","manual_review_reason")
out <- df[, cols]
write_tsv(out, out_results); write_tsv(out, out_manifest)
message("Wrote ", out_results, " and ", out_manifest)
